language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - echo 'date.timezone = "Europe/Rome"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - sudo service apache2 restart
  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
  - composer install --prefer-source
  - vendor/bin/wp core download
  - vendor/bin/wp core config --dbname=wordpress_test --dbuser=root
  - vendor/bin/wp core install --url=http://localhost/metaweblog/ --title=Test --admin_user=admin --admin_password=admin --admin_email=info@comodojo.org

script: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi;'
